version: "3.9"

services:
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "no"]
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build:
      context: ./backend
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - BASE_URL=http://localhost:8080/ticketbox
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SHORT_URL_TTL_SECONDS=${SHORT_URL_TTL_SECONDS:-0}
      - CORS_ORIGIN=*
    depends_on:
      redis:
        condition: service_healthy
    expose:
      - "3000"
    deploy:
      replicas: 1

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
